services:
  frontend:
    build:
      context: .
      args:
        - NODE_ENV=production
    restart: unless-stopped
    container_name: newstrading-frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://141.227.132.117/api/
    ports:
      - "3001:3001"
